version: "3.5"
services:
  codeceptjs:
    build:
     context: .
     shm_size: '2gb'
    container_name: 
    image: url
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /app/start.sh